// frontend/src/views/Register.tsx
import { LockAlt } from "@emotion-icons/boxicons-solid/LockAlt"
import { motion } from "framer-motion";
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { HasSavedData } from "../../wailsjs/go/main/App";
import { defaultAnimation } from "../animations/default";
import useData from "../store";

export default function Register() {

    const password = useField();
    const data = useData();
    const navigate = useNavigate()
    const repeatPassword = useField();
    const [allowSubmit, setAllowSubmit] = useState(false);
    const [errMsg, setErrMsg]= useState("");

    useEffect(() => {
        let msg = "";
        if (password.value.length > 32 || repeatPassword.value.length > 32) {
            msg = "Password must not exceed 32 characters";
            setErrMsg(msg)
            return
        }


        if (password.value != "" && repeatPassword.value != "") {
            setAllowSubmit(true);
        } else {
            setAllowSubmit(false);
        }

        setErrMsg(msg)

    }, [password.value, repeatPassword.value])


    async function handleSubmit(ev: React.FormEvent) {
        ev.preventDefault();
        if (password.value != repeatPassword.value) {
            setErrMsg("Password does not match")
            return;
        }

        try {
            await data.register(password.value)
            navigate("/dashboard")
        } catch (e) {
            console.log(e)
        }

        
    }

    return (
        <motion.div
            className="h-screen flex items-center justify-center"
            {...defaultAnimation}
        >
            <div className="bg-white rounded-lg shadow-sm flex flex-col p-14 px-14 items-center gap-5 justify-between" style={{ width: 400, height: 450 }}>
                <div className="flex flex-col gap-4 items-center">
                    <h1 className="text-lg font-semibold">Smartermail Monitor</h1>
                    <LockAlt className="" size={30} />
                    <p className="text-sm text-neutral-500 text-center">Create a password to store your server information in an encrypted format.</p>

                </div>

                <form className="flex flex-col w-full mt-5 justify-between gap-12" autoComplete="off" onSubmit={handleSubmit}>
                    <div className="flex flex-col">
                        <p className="text-red-500 text-xs mb-1 h-4">{errMsg}</p>
                        <Field className="mb-4" type="password" placeholder="Password" {...password}/>
                        <Field type="password" placeholder="Repeat Password"{...repeatPassword} />
                        
                    </div>

                    <button className="bg-blue-500 py-1.5 rounded-sm text-white font-medium" disabled={!allowSubmit} type="submit">Create</button>
                </form>

            </div>
        </motion.div>

    )
}

interface Props {
    value: string;
    type?: React.HTMLInputTypeAttribute;
    placeholder?: string;
    className?: string;
    onChange: (ev: React.ChangeEvent<HTMLInputElement>) => void;
}

function Field(props: Props) {
    return (
        <input 
            className={`bg-neutral-100 px-2.5 py-1.5 w-full rounded-sm shadow-sm text-sm outline-none ${props.className}`} 
            placeholder={props.placeholder}
            type={props.type}
            value={props.value}
            onChange={props.onChange}
        />
    )
}

function useField() {
    const [value, setValue] = useState("");

    function onChange(ev: React.ChangeEvent<HTMLInputElement>) {
        setValue(ev.target.value);
    }

    return {
        onChange,
        setValue,
        value,
    }
}

// frontend/src/routes/Register.svelte
<script type="ts">
import LockIcon from "../icons/LockIcon.svelte";

let password = "";
let repeatPassword = "";
export let register: (password: string) => void | Promise<void>;

let errorString = ""

async function handleSubmit() {
    errorString = "";


    if (password == "" || repeatPassword == "") {
        errorString = "Fields cannot be blank.";
    }

    if (password.length < 6) {
        errorString = "Password must be at least 6 characters."
    }

    if (password != repeatPassword) {
        errorString = "Password does not match.";
    }

    try {
        await register(password)
    } catch (error) {
        console.log(error)
    }
}

function resetErrorMessage() {
    errorString = ""
}


</script>
<div class="flex flex-col items-center gap-5 bg-white rounded-lg max-w-sm m-auto p-10 shadow-sm">
    <h1 class="text-2xl font-bold">Smartermail Monitor</h1>

    <div class="text-neutral-800">
        <LockIcon size={32}/>
    </div>


    <p class="text-sm text-neutral-60 text-center text-neutral-500">Create a password to store your server information in an encrypted format.</p>

    <form class="w-full flex flex-col gap-8" on:submit|preventDefault={handleSubmit}>

        <div class="flex flex-col gap-5 items-start">
            <div class="flex flex-col gap-2 w-full">
                <div class="text-xs text-red-500 h-4">{errorString}</div>
                <input bind:value={password} on:input={resetErrorMessage} class="bg-neutral-100 shadow-sm rounded-sm px-2 py-2 outline-none w-full text-sm mb-2" type="password" placeholder="Password"/>
                <input bind:value={repeatPassword} on:input={resetErrorMessage} class="bg-neutral-100 shadow-sm rounded-sm px-2 py-2 outline-none w-full text-sm" type="password" placeholder="Repeat Password"/>
            </div>
            <div class="flex flex-col items-start gap-2">
                <button class="text-blue-400 text-xs">Import data</button>
            </div>
        </div>

        <button type="submit" class="rounded-sm text-white py-2" disabled={password == "" || repeatPassword == ""}>Create</button>
    </form>

</div>
