// frontend/src/components/addserver/AddServer.svelte
<script type="ts">
  import { createEventDispatcher } from "svelte";
  import InputField from "./InputField.svelte";
  import type { ServerInfo } from '../../smartermail'

  const dispatch = createEventDispatcher();

  let host = "";
  let username = "";
  let password = "";
  let online: boolean | null = null;
  let isTestingConnection: boolean = false;
  export let handleTest: (info: ServerInfo) => Promise<boolean> | undefined = undefined;

  $: canSubmit = host != "" && username != "" && password != "";
  $: connectionColor = getConnectionColor(online);

  function getConnectionColor(x: boolean | null) {
    if (x == null) {
      return "bg-neutral-300";
    } else if (x) {
      return "bg-green-500";
    } else {
      return "bg-red-500";
    }
  }

  async function testConnection() {
    online = null;
    isTestingConnection = true;

    if (handleTest == undefined) {
      online = null;
      isTestingConnection = false;
      return;
    }

    let success = await handleTest({
      host,
      username,
      password,
    })

    console.log("Success")

    if (success) {
      online = true;
    } else {
      online = false;
    }

    isTestingConnection = false;
  }

  function handleSubmit() {
    dispatch("submit", {
      host,
      username,
      password,
    });
  }
</script>

<div class="p-8 max-w-sm w-full overflow-scroll" style="width: 400px;">
  <h1 class="text-lg font-semibold mb-4">Add Server</h1>
  <form
    class="text-sm flex flex-col gap-5"
    autocomplete="off"
    spellcheck="false"
    on:submit={handleSubmit}
    on:submit|preventDefault={() => console.log("submit")}
  >
    <InputField
      id="host-input"
      label="Host"
      bind:value={host}
      disabled={isTestingConnection}
    />
    <InputField
      id="username-input"
      label="Username"
      bind:value={username}
      disabled={isTestingConnection}
    />
    <InputField
      id="password-input"
      type="password"
      label="Password"
      bind:value={password}
      disabled={isTestingConnection}
    />

    <div class="flex flex-row items-center gap-2">
      <div
        class={`w-2 h-2 rounded-full transition-colors duration-200 ${connectionColor} ${
          isTestingConnection ? "animate-ping" : null
        }`}
      />
      <button
        on:click={testConnection}
        type="button"
        class={`text-blue-500 disabled:text-neutral-500 transition-all duration-200`}
        disabled={isTestingConnection || !canSubmit}>Test Connection</button
      >
    </div>

    <button
      type="submit"
      class="bg-blue-500 px-2 py-2 text-white rounded-sm"
      disabled={!canSubmit}>Add Server</button
    >
  </form>
</div>

// frontend/src/components/AddServer.tsx
import InputGroup from "../lib/InputGroup";
import { Close } from "@emotion-icons/material-twotone/Close"
import InputField, { useField } from "../lib/InputField";
import { FormEvent, useEffect, useState } from "react";
import useData, { ConflictError } from "../store";
import PingCircle, { PingState } from "./PingCircle";

interface Props {
    onComplete?: () => void;
}


export default function AddServer({ onComplete }: Props) {

    const addServer = useData(state => state.addServer);
    const ping = useData(state => state.ping);
    const host = useField();
    const username = useField();
    const password = useField();

    const [lockInput, setLockInput] = useState(false);
    const [allowSubmit, setAllowSubmit] = useState(false);
    const [errMsg, setErrMsg] = useState("");
    const [pingState, setPingState] = useState<PingState>("unknown");

    async function handleSubmit(ev: FormEvent) {
        ev.preventDefault();
        setLockInput(true);
        let host = cleanHost()
        try {
            await addServer(host, username.value, password.value);
            onComplete && onComplete();
        } catch (e) {
            if (e == ConflictError) {
                setErrMsg("Server is already in the list");
            }

            console.log(e)

        }
        setLockInput(false)
    }

    async function handleTestConnection() {
        cleanHost();
        setLockInput(true);
        setPingState("loading");
        const success = await ping(host.value, username.value, password.value);
        if (success) {
            setPingState("online");
        } else {
            setPingState("offline");
        }
        setLockInput(false);
    }

    function cleanHost(): string{
        const newVal = host.value.replace(/^"+|\/+$/g, "")
        host.setValue(newVal);
        return newVal;
    }

    useEffect(() => {
        if (host.value == "" || username.value == "" || password.value == "") {
            setAllowSubmit(false);
        } else {
            setAllowSubmit(true);
        }

        setPingState("unknown");

        setErrMsg("");
    }, [host.value, username.value, password.value])

    return (
        <div>
            <button className="absolute right-0 top-0 p-4">
                <Close size={24} />
            </button>
            <h1 className="font-semibold mb-4">Add Server</h1>
            <form className="flex flex-col" onSubmit={handleSubmit}>
                <InputGroup>
                    <InputField label="Host" id="host" {...host.props} errMsg={errMsg} disabled={lockInput}/>
                    <InputField label="Username" id="username" {...username.props} disabled={lockInput} />
                    <InputField label="Password" id="password" type="password" {...password.props} disabled={lockInput} />
                    <div className="flex items-center gap-2 mb-3">
                        <PingCircle state={pingState} />
                        <button
                            className="text-xs text-blue-500 disabled:text-neutral-400"
                            type="button"
                            disabled={!allowSubmit || lockInput}
                            onClick={handleTestConnection}
                        >
                            Test Connection
                        </button>
                    </div>
                    <button type="submit" disabled={!allowSubmit || lockInput}>Add Server</button>
                </InputGroup>

            </form>

        </div>
    )
}
